// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAJ-W8s0ACUtoNjKH7UGFTjros0X4IySU',
    appId: '1:920790039247:web:466a884745904afa72d5ba',
    messagingSenderId: '920790039247',
    projectId: 'foodwasteapp-b6a9f',
    authDomain: 'foodwasteapp-b6a9f.firebaseapp.com',
    storageBucket: 'foodwasteapp-b6a9f.firebasestorage.app',
    measurementId: 'G-EH2LYBXJDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWDgWi-7fL3WaVgUvi2_egYvDaoEzfRY0',
    appId: '1:920790039247:android:2dd3ba705a69ff0172d5ba',
    messagingSenderId: '920790039247',
    projectId: 'foodwasteapp-b6a9f',
    storageBucket: 'foodwasteapp-b6a9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChJlED9yn-N1Y-6-icOs8452XEWmwV0_Y',
    appId: '1:920790039247:ios:16f5a1674beae5bf72d5ba',
    messagingSenderId: '920790039247',
    projectId: 'foodwasteapp-b6a9f',
    storageBucket: 'foodwasteapp-b6a9f.firebasestorage.app',
    iosBundleId: 'com.example.foodWasteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChJlED9yn-N1Y-6-icOs8452XEWmwV0_Y',
    appId: '1:920790039247:ios:16f5a1674beae5bf72d5ba',
    messagingSenderId: '920790039247',
    projectId: 'foodwasteapp-b6a9f',
    storageBucket: 'foodwasteapp-b6a9f.firebasestorage.app',
    iosBundleId: 'com.example.foodWasteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAJ-W8s0ACUtoNjKH7UGFTjros0X4IySU',
    appId: '1:920790039247:web:30bcaa4978ce8e8e72d5ba',
    messagingSenderId: '920790039247',
    projectId: 'foodwasteapp-b6a9f',
    authDomain: 'foodwasteapp-b6a9f.firebaseapp.com',
    storageBucket: 'foodwasteapp-b6a9f.firebasestorage.app',
    measurementId: 'G-3Y293CNRMD',
  );
}
